### ISSUE TITLE
Is there any official support group on Telegram? 

### ISSUE THREAD

**Issue by sweetcock69** [adekmaulana/caligo#38]

**Comment by adekmaulana** [comment]
yes but later in master when staging merged will be anounced

**Comment by sweetcock69** [comment]
How to use aria2? I can't figure it out.

Eg. For Google Drive it's .help GoogleDrive

**Comment by adekmaulana** [comment]
> How to use aria2? I can't figure it out.
> 
> Eg. For Google Drive it's .help GoogleDrive

Aria2 don't have command yet, it's intended to use with GoogleDrive for downloading file then upload it
