### ISSUE TITLE
Any basic helps ;;

### ISSUE THREAD

**Issue by iTzBlack007** [adekmaulana/caligo#40]
What's Default command prefix // I tried to search in code but i found nothing please a telegram group or some docs help

**Comment by adekmaulana** [comment]
Default prefix for command is "."~(dot).
as it written in https://github.com/adekmaulana/caligo/blob/staging/caligo/core/telegram_bot.py#L81

**Comment by iTzBlack007** [comment]
Okay thank you 🐈❤️
