### ISSUE TITLE
Custom download path is not working properly

### ISSUE THREAD

**Issue by TomyPrs** [adekmaulana/caligo#45]
https://github.com/adekmaulana/caligo/blob/81c1f3e24974b16aac3f3b24967782b2e5a68adb/config.env_sample#L20

`[Ruffy] Magic Kaito 1412 - 01 [GER][JAP][Multi-SUB][BDRip][H.264][1080p].mkv
Status: Error
Error: Failed to make the directory "mydowload", cause: Permission denied
Code: 18`

**Comment by adekmaulana** [comment]
If running on Docker the user isn't root anymore, you are trying to use `"mydownload"` that created inside `/` directory.
so you have to use `/home/caligo/mydownload`

**Comment by TomyPrs** [comment]
:3 sure
